{
 "title": "Bolt Highlevel dashbaord Copy",
 "time": { "from": "2019-11-06T18:30:00.000Z", "to": "2019-11-07T18:29:00.000Z" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "boltanalytics-solr-datasource" },
   {
    "name": "Dashboards",
    "query": "bolt_job_config(*:*,searchGroup)"
   },
   {
    "name": "Panels",
    "query": "bolt_job_config(searchGroup: $Dashboards,name)"
   },
   { "name": "AggInterval", "label": "Aggregation Interval", "query": "+1HOUR" },
   {
    "name": "Series",
    "query": "bolt_job_config(name: $Panels, detectors)"
   },
   {
    "name": "PartitionFields",
    "label": "Partition Fields",
    "query": "bolt_an(jobId:$Panels,_timeSeriesName)"
   }
  ]
 },
 "panels": [
  {
   "title": "$Dashboards Dashboard(s)",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "aggInterval": "$AggInterval",
     "groupEnabled": "true",
     "indvAnOutField": "all",
     "numRows": 100,
     "query": "__dashboard__:$Dashboards",
     "rexOutFields": "collection,shard,replica,core,handler,params,hits,qtime",
     "rexQuery": "\\s*.*\\s*\\[c\\:(.*)\\ss\\:(.*)\\sr\\:(.*)\\sx\\:(.*)\\]\\s*o.a.s.c.S.SlowRequest.*path=(.*)\\s*params=\\{(.*)\\}\\s*.*hits=(.*)\\s*status.*QTime=(.*)"
    }
   ]
  },
  {
   "title": "$Panels Panel(s) on $Dashboards dashboard(s)",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "aggInterval": "$AggInterval",
     "groupEnabled": "false",
     "indvAnOutField": "all",
     "numRows": 100,
     "query": "__panel__:$Panels",
     "rexOutFields": "collection,shard,replica,core,handler,params,hits,qtime",
     "rexQuery": "\\s*.*\\s*\\[c\\:(.*)\\ss\\:(.*)\\sr\\:(.*)\\sx\\:(.*)\\]\\s*o.a.s.c.S.SlowRequest.*path=(.*)\\s*params=\\{(.*)\\}\\s*.*hits=(.*)\\s*status.*QTime=(.*)"
    }
   ]
  },
  {
   "title": "Distribution by partition fields for $Dashboards dashboard(s) $Panels panel(s)",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "aggInterval": "$AggInterval",
     "groupEnabled": "false",
     "indvAnOutField": "all",
     "numRows": 100,
     "query": "__panel__:$Panels AND _timeSeriesName:$PartitionFields",
     "rexOutFields": "collection,shard,replica,core,handler,params,hits,qtime",
     "rexQuery": "\\s*.*\\s*\\[c\\:(.*)\\ss\\:(.*)\\sr\\:(.*)\\sx\\:(.*)\\]\\s*o.a.s.c.S.SlowRequest.*path=(.*)\\s*params=\\{(.*)\\}\\s*.*hits=(.*)\\s*status.*QTime=(.*)"
    }
   ]
  },
  {
   "title": "All Anomalies for $Dashboards dashboard(s), $Panels panel(s) and $PartitionFields series",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggInterval": "+1HOUR",
     "groupEnabled": "false",
     "indvAnOutField": "all",
     "numRows": 100,
     "query": "__panel__:$Panels AND _timeSeriesName:$PartitionFields",
     "rexOutFields": "collection,shard,replica,core,handler,params,hits,qtime",
     "rexQuery": "\\s*.*\\s*\\[c\\:(.*)\\ss\\:(.*)\\sr\\:(.*)\\sx\\:(.*)\\]\\s*o.a.s.c.S.SlowRequest.*path=(.*)\\s*params=\\{(.*)\\}\\s*.*hits=(.*)\\s*status.*QTime=(.*)"
    }
   ]
  }
 ]
}