{
 "title": "Slow query analysis",
 "time": { "from": "2019-10-15T06:12:00.000Z", "to": "2019-10-15T06:16:00.000Z" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "boltanalytics-solr-datasource" },
   { "name": "Page", "query": "0" },
   { "name": "PageSize", "label": "Page Size", "query": "272" },
   {
    "name": "handler",
    "label": "Handler",
    "query": "\"http://192.168.33.168:8983/solr/20191011_00_shard2_replica_n2/select\""
   },
   {
    "name": "shard",
    "query": "\"http://192.168.33.168:8983/solr/20191011_00_shard2_replica_n2\""
   }
  ]
 },
 "panels": [
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "collection": "bolt",
     "groupEnabled": "false",
     "numRows": 100,
     "query": "message:\"q=*:*\" AND message:*SlowRequest*",
     "rexOutFields": "core,shard,node,replica,params,qtime",
     "rexQuery": "\\s*.*\\s*\\[c\\:(.*)\\ss\\:(.*)\\sr\\:(.*)\\sx\\:(.*)\\]\\s*o.a.s.c.S.SlowRequest.*params=\\{(.*)\\}\\s*.*QTime=(.*)"
    }
   ]
  },
  {
   "title": "Slow queries",
   "type": "briangann-datatable-panel",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "collection": "bolt",
     "fl": "message,collection,qtime,hits,shard,core,replica,handler,params,host",
     "groupEnabled": "false",
     "numRows": "$PageSize",
     "query": "message:\"q=*:*\" AND message:*SlowRequest*",
     "rexOutFields": "collection,shard,replica,core,handler,params,hits,qtime",
     "rexQuery": "\\s*.*\\s*\\[c\\:(.*)\\ss\\:(.*)\\sr\\:(.*)\\sx\\:(.*)\\]\\s*o.a.s.c.S.SlowRequest.*path=(.*)\\s*params=\\{(.*)\\}\\s*.*hits=(.*)\\s*status.*QTime=(.*)",
     "sortField": "timestamp",
     "sortOrder": "desc",
     "start": "$Page"
    }
   ]
  },
  {
   "title": "Average request time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggInterval": "+1HOUR",
     "groupEnabled": "false",
     "indvAnOutField": "all",
     "numRows": 100,
     "query": "jobId:\"Core_Metrics_Average_Request_Time_Slow_Query_-_v1\" AND aggr_field:$handler",
     "rexOutFields": "collection,shard,replica,core,handler,params,hits,qtime",
     "rexQuery": "\\s*.*\\s*\\[c\\:(.*)\\ss\\:(.*)\\sr\\:(.*)\\sx\\:(.*)\\]\\s*o.a.s.c.S.SlowRequest.*path=(.*)\\s*params=\\{(.*)\\}\\s*.*hits=(.*)\\s*status.*QTime=(.*)"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggInterval": "+1HOUR",
     "groupEnabled": "false",
     "indvAnOutField": "all",
     "numRows": 100,
     "query": "jobId:\"Core_Metrics_Requests_Slow_Query_-_v1\" AND aggr_field:$handler",
     "rexOutFields": "collection,shard,replica,core,handler,params,hits,qtime",
     "rexQuery": "\\s*.*\\s*\\[c\\:(.*)\\ss\\:(.*)\\sr\\:(.*)\\sx\\:(.*)\\]\\s*o.a.s.c.S.SlowRequest.*path=(.*)\\s*params=\\{(.*)\\}\\s*.*hits=(.*)\\s*status.*QTime=(.*)"
    }
   ]
  },
  {
   "title": "Update commits",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggInterval": "+1HOUR",
     "groupEnabled": "false",
     "indvAnOutField": "all",
     "numRows": 100,
     "query": "jobId:Core_Metrics_Update_Handler_Commits_Slow_Query_-_v1 AND aggr_field:$shard",
     "rexOutFields": "collection,shard,replica,core,handler,params,hits,qtime",
     "rexQuery": "\\s*.*\\s*\\[c\\:(.*)\\ss\\:(.*)\\sr\\:(.*)\\sx\\:(.*)\\]\\s*o.a.s.c.S.SlowRequest.*path=(.*)\\s*params=\\{(.*)\\}\\s*.*hits=(.*)\\s*status.*QTime=(.*)"
    }
   ]
  },
  {
   "title": "Request time P95",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggInterval": "+1HOUR",
     "groupEnabled": "false",
     "indvAnOutField": "all",
     "numRows": 100,
     "query": "jobId:\"Core_Metrics_Request_Time_p95_Slow_Query_-_v1\" AND aggr_field:$handler",
     "rexOutFields": "collection,shard,replica,core,handler,params,hits,qtime",
     "rexQuery": "\\s*.*\\s*\\[c\\:(.*)\\ss\\:(.*)\\sr\\:(.*)\\sx\\:(.*)\\]\\s*o.a.s.c.S.SlowRequest.*path=(.*)\\s*params=\\{(.*)\\}\\s*.*hits=(.*)\\s*status.*QTime=(.*)"
    }
   ]
  },
  {
   "title": "Total request time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggInterval": "+1HOUR",
     "groupEnabled": "false",
     "indvAnOutField": "all",
     "numRows": 100,
     "query": "jobId:Core_Metrics_Total_Request_Time_Slow_Query_-_v1 AND aggr_field:$handler",
     "rexOutFields": "collection,shard,replica,core,handler,params,hits,qtime",
     "rexQuery": "\\s*.*\\s*\\[c\\:(.*)\\ss\\:(.*)\\sr\\:(.*)\\sx\\:(.*)\\]\\s*o.a.s.c.S.SlowRequest.*path=(.*)\\s*params=\\{(.*)\\}\\s*.*hits=(.*)\\s*status.*QTime=(.*)"
    }
   ]
  },
  {
   "title": "Index size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggInterval": "+1HOUR",
     "groupEnabled": "false",
     "indvAnOutField": "all",
     "numRows": 100,
     "query": "jobId:\"Core_Metrics_Index_Size_Slow_Query_-_v1\" AND aggr_field:$shard",
     "rexOutFields": "collection,shard,replica,core,handler,params,hits,qtime",
     "rexQuery": "\\s*.*\\s*\\[c\\:(.*)\\ss\\:(.*)\\sr\\:(.*)\\sx\\:(.*)\\]\\s*o.a.s.c.S.SlowRequest.*path=(.*)\\s*params=\\{(.*)\\}\\s*.*hits=(.*)\\s*status.*QTime=(.*)"
    }
   ]
  },
  {
   "title": "JVM GC Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggInterval": "+1HOUR",
     "groupEnabled": "false",
     "indvAnOutField": "all",
     "numRows": 100,
     "query": "jobId:JVM_Metrics_GC_Count_Slow_Query_-_v1",
     "rexOutFields": "collection,shard,replica,core,handler,params,hits,qtime",
     "rexQuery": "\\s*.*\\s*\\[c\\:(.*)\\ss\\:(.*)\\sr\\:(.*)\\sx\\:(.*)\\]\\s*o.a.s.c.S.SlowRequest.*path=(.*)\\s*params=\\{(.*)\\}\\s*.*hits=(.*)\\s*status.*QTime=(.*)"
    }
   ]
  },
  {
   "title": "JVM GC Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggInterval": "+1HOUR",
     "groupEnabled": "false",
     "indvAnOutField": "all",
     "numRows": 100,
     "query": "jobId:\"JVM_Metrics_GC_Time_Slow_Query_-_v1\"",
     "rexOutFields": "collection,shard,replica,core,handler,params,hits,qtime",
     "rexQuery": "\\s*.*\\s*\\[c\\:(.*)\\ss\\:(.*)\\sr\\:(.*)\\sx\\:(.*)\\]\\s*o.a.s.c.S.SlowRequest.*path=(.*)\\s*params=\\{(.*)\\}\\s*.*hits=(.*)\\s*status.*QTime=(.*)"
    }
   ]
  },
  {
   "title": "JVM Heap size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggInterval": "+1HOUR",
     "groupEnabled": "false",
     "indvAnOutField": "all",
     "numRows": 100,
     "query": "jobId:\"JVM_Metrics_Heap_Size_Slow_Query_-_v1\"",
     "rexOutFields": "collection,shard,replica,core,handler,params,hits,qtime",
     "rexQuery": "\\s*.*\\s*\\[c\\:(.*)\\ss\\:(.*)\\sr\\:(.*)\\sx\\:(.*)\\]\\s*o.a.s.c.S.SlowRequest.*path=(.*)\\s*params=\\{(.*)\\}\\s*.*hits=(.*)\\s*status.*QTime=(.*)"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggInterval": "+1HOUR",
     "groupEnabled": "false",
     "indvAnOutField": "all",
     "numRows": 100,
     "query": "jobId:\"OS_Metrics_Load_Average_Slow_Query_-_v1\"",
     "rexOutFields": "collection,shard,replica,core,handler,params,hits,qtime",
     "rexQuery": "\\s*.*\\s*\\[c\\:(.*)\\ss\\:(.*)\\sr\\:(.*)\\sx\\:(.*)\\]\\s*o.a.s.c.S.SlowRequest.*path=(.*)\\s*params=\\{(.*)\\}\\s*.*hits=(.*)\\s*status.*QTime=(.*)"
    }
   ]
  },
  {
   "title": "Node request time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggInterval": "+1HOUR",
     "groupEnabled": "false",
     "indvAnOutField": "all",
     "numRows": 100,
     "query": "jobId:\"Node_Metrics_Request_Time_Slow_Query_-_v1\"",
     "rexOutFields": "collection,shard,replica,core,handler,params,hits,qtime",
     "rexQuery": "\\s*.*\\s*\\[c\\:(.*)\\ss\\:(.*)\\sr\\:(.*)\\sx\\:(.*)\\]\\s*o.a.s.c.S.SlowRequest.*path=(.*)\\s*params=\\{(.*)\\}\\s*.*hits=(.*)\\s*status.*QTime=(.*)"
    }
   ]
  },
  {
   "title": "Node requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggInterval": "+1HOUR",
     "groupEnabled": "false",
     "indvAnOutField": "all",
     "numRows": 100,
     "query": "jobId:\"Node_Metrics_Requests_Slow_Query_-_v1\"",
     "rexOutFields": "collection,shard,replica,core,handler,params,hits,qtime",
     "rexQuery": "\\s*.*\\s*\\[c\\:(.*)\\ss\\:(.*)\\sr\\:(.*)\\sx\\:(.*)\\]\\s*o.a.s.c.S.SlowRequest.*path=(.*)\\s*params=\\{(.*)\\}\\s*.*hits=(.*)\\s*status.*QTime=(.*)"
    }
   ]
  },
  {
   "title": "Correlated metrics",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "baseMetric": "Bolt_Row_max_p99____Solr_Dashboard",
     "groupEnabled": "false",
     "numRows": 100,
     "query": "jobId:*",
     "rexOutFields": "collection,shard,replica,core,handler,params,hits,qtime",
     "rexQuery": "\\s*.*\\s*\\[c\\:(.*)\\ss\\:(.*)\\sr\\:(.*)\\sx\\:(.*)\\]\\s*o.a.s.c.S.SlowRequest.*path=(.*)\\s*params=\\{(.*)\\}\\s*.*hits=(.*)\\s*status.*QTime=(.*)"
    }
   ]
  }
 ]
}